baseurl = "http://diskstation2/myblog/"
theme = "hugo_theme_robust-master"
buildDrafts = true
preserveTaxonomyNames = true
title= "www.mauvaisetroupe.com"
Paginate = 100

[taxonomies]
pays = "pays"
voyage = "voyages"

