//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.25 at 10:01:27 AM CEST 
//

package com.mauvaisetroupe.tdm.input;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Country" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Page" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="Picture">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="town" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="place" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Content">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="folder" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Content" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="folder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dicoSet">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dico" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="geography" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="climate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="_row" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="area" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="population" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                           &lt;attribute name="official" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="local" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Xfranc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Xfrance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="capitale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ISO4217" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ofThe" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="in" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Xml">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="folder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "country", "dicoSet", "xml" })
@XmlRootElement(name = "Root")
public class Root {

    @XmlElement(name = "Country")
    protected List<Root.Country> country;
    @XmlElement(required = true)
    protected Root.DicoSet dicoSet;
    @XmlElement(name = "Xml", required = true)
    protected Root.Xml xml;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "folder")
    protected String folder;
    @XmlAttribute(name = "level")
    protected Byte level;
    @XmlAttribute(name = "path")
    protected String path;

    /**
     * Gets the value of the country property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the country property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCountry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Root.Country }
     * 
     * 
     */
    public List<Root.Country> getCountry() {
        if (country == null) {
            country = new ArrayList<Root.Country>();
        }
        return this.country;
    }

    /**
     * Gets the value of the dicoSet property.
     * 
     * @return possible object is {@link Root.DicoSet }
     * 
     */
    public Root.DicoSet getDicoSet() {
        return dicoSet;
    }

    /**
     * Sets the value of the dicoSet property.
     * 
     * @param value
     *            allowed object is {@link Root.DicoSet }
     * 
     */
    public void setDicoSet(Root.DicoSet value) {
        this.dicoSet = value;
    }

    /**
     * Gets the value of the xml property.
     * 
     * @return possible object is {@link Root.Xml }
     * 
     */
    public Root.Xml getXml() {
        return xml;
    }

    /**
     * Sets the value of the xml property.
     * 
     * @param value
     *            allowed object is {@link Root.Xml }
     * 
     */
    public void setXml(Root.Xml value) {
        this.xml = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the folder property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFolder() {
        return folder;
    }

    /**
     * Sets the value of the folder property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFolder(String value) {
        this.folder = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return possible object is {@link Byte }
     * 
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *            allowed object is {@link Byte }
     * 
     */
    public void setLevel(Byte value) {
        this.level = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Page" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="Picture">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="town" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="place" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Content">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="folder" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Content" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="folder" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "page", "content" })
    public static class Country {

        @Override
        public String toString() {
            return "Country [page=" + page + ", content=" + content + ", id=" + id + ", folder=" + folder + ", level=" + level + ", name=" + name + ", path=" + path + "]";
        }

        @XmlElement(name = "Page")
        protected List<Root.Country.Page> page;
        @XmlElement(name = "Content")
        protected Root.Country.Content content;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "folder")
        protected String folder;
        @XmlAttribute(name = "level")
        protected Byte level;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "path")
        protected String path;

        /**
         * Gets the value of the page property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the page property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getPage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Root.Country.Page }
         * 
         * 
         */
        public List<Root.Country.Page> getPage() {
            if (page == null) {
                page = new ArrayList<Root.Country.Page>();
            }
            return this.page;
        }

        /**
         * Gets the value of the content property.
         * 
         * @return possible object is {@link Root.Country.Content }
         * 
         */
        public Root.Country.Content getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *            allowed object is {@link Root.Country.Content }
         * 
         */
        public void setContent(Root.Country.Content value) {
            this.content = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the folder property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getFolder() {
            return folder;
        }

        /**
         * Sets the value of the folder property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setFolder(String value) {
            this.folder = value;
        }

        /**
         * Gets the value of the level property.
         * 
         * @return possible object is {@link Byte }
         * 
         */
        public Byte getLevel() {
            return level;
        }

        /**
         * Sets the value of the level property.
         * 
         * @param value
         *            allowed object is {@link Byte }
         * 
         */
        public void setLevel(Byte value) {
            this.level = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the path property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setPath(String value) {
            this.path = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "value" })
        public static class Content {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "title")
            protected String title;
            @XmlAttribute(name = "path")
            protected String path;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the value property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the path property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getPath() {
                return path;
            }

            /**
             * Sets the value of the path property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setPath(String value) {
                this.path = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setId(String value) {
                this.id = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="Picture">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="town" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="place" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Content">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="folder" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "pictureOrContent" })
        public static class Page {

            @XmlElements({ @XmlElement(name = "Picture", type = Root.Country.Page.Picture.class), @XmlElement(name = "Content", type = Root.Country.Page.Content.class) })
            protected List<Object> pictureOrContent;
            @XmlAttribute(name = "id")
            protected Byte id;
            @XmlAttribute(name = "folder")
            protected Byte folder;
            @XmlAttribute(name = "level")
            protected Byte level;
            @XmlAttribute(name = "order")
            protected Byte order;
            @XmlAttribute(name = "path")
            protected String path;

            /**
             * Gets the value of the pictureOrContent property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why
             * there is not a <CODE>set</CODE> method for the pictureOrContent property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getPictureOrContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link Root.Country.Page.Picture } {@link Root.Country.Page.Content }
             * 
             * 
             */
            public List<Object> getPictureOrContent() {
                if (pictureOrContent == null) {
                    pictureOrContent = new ArrayList<Object>();
                }
                return this.pictureOrContent;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return possible object is {@link Byte }
             * 
             */
            public Byte getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *            allowed object is {@link Byte }
             * 
             */
            public void setId(Byte value) {
                this.id = value;
            }

            /**
             * Gets the value of the folder property.
             * 
             * @return possible object is {@link Byte }
             * 
             */
            public Byte getFolder() {
                return folder;
            }

            /**
             * Sets the value of the folder property.
             * 
             * @param value
             *            allowed object is {@link Byte }
             * 
             */
            public void setFolder(Byte value) {
                this.folder = value;
            }

            /**
             * Gets the value of the level property.
             * 
             * @return possible object is {@link Byte }
             * 
             */
            public Byte getLevel() {
                return level;
            }

            /**
             * Sets the value of the level property.
             * 
             * @param value
             *            allowed object is {@link Byte }
             * 
             */
            public void setLevel(Byte value) {
                this.level = value;
            }

            /**
             * Gets the value of the order property.
             * 
             * @return possible object is {@link Byte }
             * 
             */
            public Byte getOrder() {
                return order;
            }

            /**
             * Sets the value of the order property.
             * 
             * @param value
             *            allowed object is {@link Byte }
             * 
             */
            public void setOrder(Byte value) {
                this.order = value;
            }

            /**
             * Gets the value of the path property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getPath() {
                return path;
            }

            /**
             * Sets the value of the path property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setPath(String value) {
                this.path = value;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * 
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "value" })
            public static class Content {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "title")
                protected String title;
                @XmlAttribute(name = "path")
                protected String path;
                @XmlAttribute(name = "id")
                protected String id;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the title property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getTitle() {
                    return title;
                }

                /**
                 * Sets the value of the title property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setTitle(String value) {
                    this.title = value;
                }

                /**
                 * Gets the value of the path property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getPath() {
                    return path;
                }

                /**
                 * Sets the value of the path property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setPath(String value) {
                    this.path = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setId(String value) {
                    this.id = value;
                }

            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * 
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="town" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="place" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "value" })
            public static class Picture {

                @Override
                public String toString() {
                    //return "Picture [value=" + value + ", date=" + date + ", id=" + id + ", town=" + town + ", place=" + place + ", description=" + description + ", country=" + country + "]";
                	return "Picture [id=" + id + "]";
                }

                @XmlValue
                protected String value;
                @XmlAttribute(name = "date")
                protected String date;
                @XmlAttribute(name = "id")
                protected String id;
                @XmlAttribute(name = "town")
                protected String town;
                @XmlAttribute(name = "place")
                protected String place;
                @XmlAttribute(name = "description")
                protected String description;
                @XmlAttribute(name = "country")
                protected String country;
                
                protected String path;

                public String getPath() {
					return path;
				}

				public void setPath(String path) {
					this.path = path;
				}

				/**
                 * Gets the value of the value property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the date property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getDate() {
                    return date;
                }

                /**
                 * Sets the value of the date property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setDate(String value) {
                    this.date = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the town property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getTown() {
                    return town;
                }

                /**
                 * Sets the value of the town property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setTown(String value) {
                    this.town = value;
                }

                /**
                 * Gets the value of the place property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getPlace() {
                    return place;
                }

                /**
                 * Sets the value of the place property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setPlace(String value) {
                    this.place = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the country property.
                 * 
                 * @return possible object is {@link String }
                 * 
                 */
                public String getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 * 
                 */
                public void setCountry(String value) {
                    this.country = value;
                }

            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dico" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="geography" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="climate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="_row" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="area" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="population" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                 &lt;attribute name="official" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="local" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Xfranc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Xfrance" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="capitale" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ISO4217" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ofThe" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="in" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "dico" })
    public static class DicoSet {

        protected List<Root.DicoSet.Dico> dico;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the dico property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the dico property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getDico().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Root.DicoSet.Dico }
         * 
         * 
         */
        public List<Root.DicoSet.Dico> getDico() {
            if (dico == null) {
                dico = new ArrayList<Root.DicoSet.Dico>();
            }
            return this.dico;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="geography" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="climate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="_row" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="area" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="population" type="{http://www.w3.org/2001/XMLSchema}short" />
         *       &lt;attribute name="official" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="local" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Xfranc" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Xfrance" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="capitale" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ISO4217" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ofThe" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="in" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "content" })
        public static class Dico {

            @XmlElementRefs({ @XmlElementRef(name = "geography", type = JAXBElement.class), @XmlElementRef(name = "climate", type = JAXBElement.class) })
            @XmlMixed
            protected List<Serializable> content;
            @XmlAttribute(name = "_row")
            protected Byte row;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "area")
            protected Integer area;
            @XmlAttribute(name = "population")
            protected Short population;
            @XmlAttribute(name = "official")
            protected String official;
            @XmlAttribute(name = "local")
            protected String local;
            @XmlAttribute(name = "Xfranc")
            protected String xfranc;
            @XmlAttribute(name = "Xfrance")
            protected String xfrance;
            @XmlAttribute(name = "capitale")
            protected String capitale;
            @XmlAttribute(name = "language")
            protected String language;
            @XmlAttribute(name = "currency")
            protected String currency;
            @XmlAttribute(name = "ISO4217")
            protected String iso4217;
            @XmlAttribute(name = "ofThe")
            protected String ofThe;
            @XmlAttribute(name = "in")
            protected String in;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why
             * there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link String }{@code >} {@link String } {@link JAXBElement }{@code <}{@link String }{@code >}
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

            /**
             * Gets the value of the row property.
             * 
             * @return possible object is {@link Byte }
             * 
             */
            public Byte getRow() {
                return row;
            }

            /**
             * Sets the value of the row property.
             * 
             * @param value
             *            allowed object is {@link Byte }
             * 
             */
            public void setRow(Byte value) {
                this.row = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the area property.
             * 
             * @return possible object is {@link Integer }
             * 
             */
            public Integer getArea() {
                return area;
            }

            /**
             * Sets the value of the area property.
             * 
             * @param value
             *            allowed object is {@link Integer }
             * 
             */
            public void setArea(Integer value) {
                this.area = value;
            }

            /**
             * Gets the value of the population property.
             * 
             * @return possible object is {@link Short }
             * 
             */
            public Short getPopulation() {
                return population;
            }

            /**
             * Sets the value of the population property.
             * 
             * @param value
             *            allowed object is {@link Short }
             * 
             */
            public void setPopulation(Short value) {
                this.population = value;
            }

            /**
             * Gets the value of the official property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getOfficial() {
                return official;
            }

            /**
             * Sets the value of the official property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setOfficial(String value) {
                this.official = value;
            }

            /**
             * Gets the value of the local property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getLocal() {
                return local;
            }

            /**
             * Sets the value of the local property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setLocal(String value) {
                this.local = value;
            }

            /**
             * Gets the value of the xfranc property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getXfranc() {
                return xfranc;
            }

            /**
             * Sets the value of the xfranc property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setXfranc(String value) {
                this.xfranc = value;
            }

            /**
             * Gets the value of the xfrance property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getXfrance() {
                return xfrance;
            }

            /**
             * Sets the value of the xfrance property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setXfrance(String value) {
                this.xfrance = value;
            }

            /**
             * Gets the value of the capitale property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getCapitale() {
                return capitale;
            }

            /**
             * Sets the value of the capitale property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setCapitale(String value) {
                this.capitale = value;
            }

            /**
             * Gets the value of the language property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getLanguage() {
                return language;
            }

            /**
             * Sets the value of the language property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setLanguage(String value) {
                this.language = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the iso4217 property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getISO4217() {
                return iso4217;
            }

            /**
             * Sets the value of the iso4217 property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setISO4217(String value) {
                this.iso4217 = value;
            }

            /**
             * Gets the value of the ofThe property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getOfThe() {
                return ofThe;
            }

            /**
             * Sets the value of the ofThe property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setOfThe(String value) {
                this.ofThe = value;
            }

            /**
             * Gets the value of the in property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getIn() {
                return in;
            }

            /**
             * Sets the value of the in property.
             * 
             * @param value
             *            allowed object is {@link String }
             * 
             */
            public void setIn(String value) {
                this.in = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Xml {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "path")
        protected String path;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the path property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setPath(String value) {
            this.path = value;
        }

    }

}
